### ISSUE TITLE
안녕하세요~

### ISSUE THREAD

**Issue by circumeo** [eungbean/Alfred-Papago-Workflow#6]
그동안 감사하게도 워크플로우 잘 사용중이 한 사람이었습니다.

그런데 오늘 실행해보니 아래와 같은 오류가 발생됩니다.

혹시 원인이 뭘까요 ㅠㅠ

`[18:21:08.386] Logging Started...
[18:21:11.847] Papago[Script Filter] Queuing argument '안녕'
[18:21:12.130] Papago[Script Filter] Script with argv '안녕' finished
[18:21:12.138] ERROR: Papago[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/greedist/Library/Mobile Documents/com~apple~CloudDocs/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.0F448747-CF61-468D-BD03-C3199F12A28F/ppg.py", line 120, in <module>
    main()
  File "/Users/greedist/Library/Mobile Documents/com~apple~CloudDocs/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.0F448747-CF61-468D-BD03-C3199F12A28F/ppg.py", line 88, in main
    output_json = get_translated_data(str(inputString))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/greedist/Library/Mobile Documents/com~apple~CloudDocs/Sync/Alfred/Alfred.alfredpreferences/workflows/user.workflow.0F448747-CF61-468D-BD03-C3199F12A28F/ppg.py", line 53, in get_translated_data
    response = urllib.request.urlopen(request, data=data.encode("utf-8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests`

**Comment by circumeo** [comment]
api clinet id 및 secret key 재설정으로 해결했습니다 ^^
